[package]
name = "endiannezz_derive"
version = "0.2.2"
authors = ["Frago9876543210"]
edition = "2018"
license = "MIT"
description = "Addition to endiannezz crate that allows derive(Io)"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
