name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-${{ matrix.toolchain }}-cargo-${{ hashFiles('Cargo.toml') }}

      - name: Setup ${{ matrix.toolchain }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
